/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package bitmap.transformer;

import javax.imageio.ImageIO;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;

public class App {

    public static void main(String[] args) {

        Bitmap image01 = new Bitmap("assets/io-image.jpg",
                "assets/",
                "Black&White.jpg");

        image01.bitTransformBlackWhite();

        Bitmap image02 = new Bitmap("assets/io-image.jpg",
                "assets/",
                "waterMark.jpg");

        image02.waterMark();

        Bitmap image03 = new Bitmap("assets/io-image.jpg",
                "assets/",
                "waterMark.jpg");

        image03.getSetPixels();
    }
}
